### ISSUE TITLE
Do we need `edges_undirected`?

### ISSUE THREAD

**Issue by ShivanKaul** [brave/pagegraph-rust#27]
Just realized our `petgraph` dependency is actually to a fork: https://github.com/brave/pagegraph-rust/blame/main/pagegraph/Cargo.toml#L10. Do we still need the fork? It doesn't look like we use `edges_undirected` anywhere.

**Comment by antonok-edm** [comment]
close?

**Comment by ShivanKaul** [comment]
We updated the dep.
